### PR TITLE
Commands through Plugins

### PR DESCRIPTION
**Pull request by Spartan322**
Gives anyone the ability to create a Plugin with Commands (The Plugin and Command do not recognize each other yet)
Works simlilar to Minecraft Bukkit Server Commands. (There is currently only one function that exists so there aren't reactions yet)

Also could someone check my code (I am a C++ Programmer and I can't check it currently)

### CODE REVIEW

**Comment by chessmaster42** [comment]
I really like where this is going and what you're doing. However this code won't even compile. You have a number of errors. Please make sure that whatever you are submitting compiles and works in the server tool.

**Comment by Spartan322** [comment]
I expected that to happen. I will see what goes on. Thanks for the input

**Comment by Spartan322** [comment]
Did I fix it? I have gotten some of the issues at least solved but I am not sure is it is good to go. (Can not compile it)

**Comment by fvgoulet** [comment]
Use MSBuild. Its the compiler that is used by Visual Studio. It is simply less forgiving than VS.
http://stackoverflow.com/questions/2567018/installing-msbuild-4-0-without-visual-studio-2010

I'll check your code this week-end if you can't manage to compile it with MSBuild.

**Comment by Spartan322** [comment]
Unfortunately I can not install MSBuild. My computer currently does not let me do that

**Comment by generalwrex** [comment]
Are you on a limited user account that wont allow you to install programs?  What are you using to write the code?

**Comment by Spartan322** [comment]
Yes and I use a visual studio 2008 tool program that checks the validity of the code but has no compiler and notepad++

**Comment by generalwrex** [comment]
Is there any way at all you can get elevated privileges?

**Comment by chessmaster42** [comment]
We will not be merging in this code until you are able to compile and test this independently. We will be more than happy to review and merge again later.

**Comment by Spartan322** [comment]
k

**Pull request closed without merging**
